version: "3.9"

services:
  # Service PostgreSQL
  postgres:
    image: postgres:15
    container_name: myevent-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: myeventdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"  

  # Service Backend (API Express)
  backend:
    build: ./backend
    container_name: myevent-backend
    ports:
      - "8084:3000" 
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: myeventdb
      DB_USER: myuser
      DB_PASSWORD: mypass
    depends_on:
      - postgres

  # Service Frontend (React)
  frontend:
    build: ./frontend
    container_name: myevent-frontend
    ports:
      - "9004:80" 
    depends_on:
      - backend

volumes:
  pgdata:
